module.exports = {
  GuildSchema: {
    prefix: 'f.',
    premium: false,
    ideaChannel: null,
    ideaBlacklist: [],
    warnings: [],
    settings: {
      clearCommandCalls: false,
      deleteUserAfterLeave: false,
      answerOnDisabledCommands: false,
      hideDisabledCommands: false,
    },
    ideas: [],
    welcome: {
      enabled: false,
      text: null,
      channel: null,
    },
    leave: {
      enabled: false,
      text: null,
      channel: null,
    },
    welcomeRole: null,
    currency: '$',
    work: { min: 100, max: 400 },
    items: [],
    pickaxes: [],
    rods: [],
    cooldown: {
      work: 3600 * 3,
      crime: 3600 * 5,
      rob: 3600 * 24,
      fish: 3600 * 3,
      mine: 3600 * 5,
    },
    moderator: null,
    muteRole: null,
    disabledCommands: [],
    antiInvite: {
      enabled: false,
      message: null,
      whiteList: [],
    },
  },
  UserSchema: {
    money: 0,
    bank: 0,
    ownedPickaxes: [],
    ownedRods: [],
    ownedTransport: [],
    payments: {
      list: [],
      blocked: false,
    },
  },
};
